services:
  terminal:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: digital-oreon:humble
    network_mode: host
    privileged: true
    user: "1000:1000"
    stdin_open: true
    tty: true

    # работаем в домашнем каталоге пользователя (а не /root)
    working_dir: /home/mobile/ros2_ws

    volumes:
      # ваш рабочий каталог в контейнере
      - ..:/home/mobile/ros2_ws:rw

      # WSLg: обязательно монтируем /mnt/wslg и X-сокет
      - /mnt/wslg:/mnt/wslg:rw
      - /mnt/wslg/.X11-unix:/tmp/.X11-unix:rw

      # опционально (если есть /dev/dri)
      - /dev/dri:/dev/dri:rw
      - /mnt/c/Users/romax/OneDrive/Документы/QGroundControl/Logs:/home/mobile/ros2_ws/qgc_logs:ro

    environment:
      # прокидываем GUI переменные из WSL (обязательно фигурные скобки)
      - DISPLAY=${DISPLAY}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir
      - PULSE_SERVER=/mnt/wslg/PulseServer

      # устойчивость Qt/X11 под WSLg
      - QT_QPA_PLATFORM=xcb
      - QT_X11_NO_MITSHM=1

      # можно оставить, если есть проблемы с OpenGL
      - LIBGL_ALWAYS_SOFTWARE=1

      # по желанию: Gazebo master на localhost
      - GAZEBO_IP=127.0.0.1
      - GAZEBO_MASTER_URI=http://127.0.0.1:11345

      # CycloneDDS
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - RMW_CYCLONEDDS_USE_SHM=0

    entrypoint:
      - /bin/bash
      - -lc
      - |
        source /opt/ros/humble/setup.bash
        exec bash

# apt-get update && apt-get install -y x11-apps
# echo $DISPLAY                # должно показать :0
# ls -l /tmp/.X11-unix         # должен быть сокет X0
# xclock                       # должно открыть окно на рабочем столе Windows
